package example.app.entity;

import java.util.Date;

public class DatMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.code
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.date
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.password
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.name
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.email
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.postal1
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String postal1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.postal2
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String postal2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.address
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.tel
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.danjyo
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private Integer danjyo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_member.birth
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    private Integer birth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.code
     *
     * @return the value of dat_member.code
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.code
     *
     * @param code the value for dat_member.code
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.date
     *
     * @return the value of dat_member.date
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.date
     *
     * @param date the value for dat_member.date
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.password
     *
     * @return the value of dat_member.password
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.password
     *
     * @param password the value for dat_member.password
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.name
     *
     * @return the value of dat_member.name
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.name
     *
     * @param name the value for dat_member.name
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.email
     *
     * @return the value of dat_member.email
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.email
     *
     * @param email the value for dat_member.email
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.postal1
     *
     * @return the value of dat_member.postal1
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getPostal1() {
        return postal1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.postal1
     *
     * @param postal1 the value for dat_member.postal1
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setPostal1(String postal1) {
        this.postal1 = postal1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.postal2
     *
     * @return the value of dat_member.postal2
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getPostal2() {
        return postal2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.postal2
     *
     * @param postal2 the value for dat_member.postal2
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setPostal2(String postal2) {
        this.postal2 = postal2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.address
     *
     * @return the value of dat_member.address
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.address
     *
     * @param address the value for dat_member.address
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.tel
     *
     * @return the value of dat_member.tel
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.tel
     *
     * @param tel the value for dat_member.tel
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.danjyo
     *
     * @return the value of dat_member.danjyo
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public Integer getDanjyo() {
        return danjyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.danjyo
     *
     * @param danjyo the value for dat_member.danjyo
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setDanjyo(Integer danjyo) {
        this.danjyo = danjyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_member.birth
     *
     * @return the value of dat_member.birth
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public Integer getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_member.birth
     *
     * @param birth the value for dat_member.birth
     *
     * @mbggenerated Tue Mar 27 21:11:54 AEDT 2018
     */
    public void setBirth(Integer birth) {
        this.birth = birth;
    }
}