package example.app.entity;

import example.app.entity.DatSalesProduct;
import example.app.entity.DatSalesProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatSalesProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int countByExample(DatSalesProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int deleteByExample(DatSalesProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int insert(DatSalesProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int insertSelective(DatSalesProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    List<DatSalesProduct> selectByExample(DatSalesProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    DatSalesProduct selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") DatSalesProduct record, @Param("example") DatSalesProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByExample(@Param("record") DatSalesProduct record, @Param("example") DatSalesProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByPrimaryKeySelective(DatSalesProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales_product
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByPrimaryKey(DatSalesProduct record);
}