package example.app.entity;

import java.util.Date;

public class DatSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.code
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.date
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.code_number
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private Integer codeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.name
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.email
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.postal1
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private String postal1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.postal2
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private String postal2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.address
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_sales.tel
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.code
     *
     * @return the value of dat_sales.code
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.code
     *
     * @param code the value for dat_sales.code
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.date
     *
     * @return the value of dat_sales.date
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.date
     *
     * @param date the value for dat_sales.date
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.code_number
     *
     * @return the value of dat_sales.code_number
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public Integer getCodeNumber() {
        return codeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.code_number
     *
     * @param codeNumber the value for dat_sales.code_number
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setCodeNumber(Integer codeNumber) {
        this.codeNumber = codeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.name
     *
     * @return the value of dat_sales.name
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.name
     *
     * @param name the value for dat_sales.name
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.email
     *
     * @return the value of dat_sales.email
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.email
     *
     * @param email the value for dat_sales.email
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.postal1
     *
     * @return the value of dat_sales.postal1
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public String getPostal1() {
        return postal1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.postal1
     *
     * @param postal1 the value for dat_sales.postal1
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setPostal1(String postal1) {
        this.postal1 = postal1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.postal2
     *
     * @return the value of dat_sales.postal2
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public String getPostal2() {
        return postal2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.postal2
     *
     * @param postal2 the value for dat_sales.postal2
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setPostal2(String postal2) {
        this.postal2 = postal2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.address
     *
     * @return the value of dat_sales.address
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.address
     *
     * @param address the value for dat_sales.address
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_sales.tel
     *
     * @return the value of dat_sales.tel
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_sales.tel
     *
     * @param tel the value for dat_sales.tel
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }
}