package example.app.entity;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DatSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int countByExample(DatSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int deleteByExample(DatSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int insert(DatSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int insertSelective(DatSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    List<DatSales> selectByExample(DatSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    DatSales selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") DatSales record, @Param("example") DatSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByExample(@Param("record") DatSales record, @Param("example") DatSalesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByPrimaryKeySelective(DatSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_sales
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByPrimaryKey(DatSales record);
    int getLastCode();

    int insertAndGetCode(DatSales record);
}