package example.app.entity;

import example.app.entity.MstStaff;
import example.app.entity.MstStaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MstStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int countByExample(MstStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int deleteByExample(MstStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int insert(MstStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int insertSelective(MstStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    List<MstStaff> selectByExample(MstStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    MstStaff selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") MstStaff record, @Param("example") MstStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByExample(@Param("record") MstStaff record, @Param("example") MstStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByPrimaryKeySelective(MstStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_staff
     *
     * @mbggenerated Sun Mar 25 02:24:53 AEDT 2018
     */
    int updateByPrimaryKey(MstStaff record);
}